apiVersion: apps/v1
kind: Deployment
metadata:
  name: tide-info
  labels:
    app: tide-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tide-info
  template:
    metadata:
      labels:
        app: tide-info
    spec:
      containers:
        - name: tide-info
          image: "username/tide-info:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
