apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-booking
  labels:
    app: reservation-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-booking
  template:
    metadata:
      labels:
        app: reservation-booking
    spec:
      containers:
        - name: reservation-booking
          image: "username/reservation-booking:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
