apiVersion: v1
kind: Service
metadata:
  name: reservation-booking
  labels:
    app: reservation-booking
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservation-booking