name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./reservation-booking/pom.xml
          mvn clean package -f ./transfer-reservation/pom.xml
          mvn clean package -f ./weather-info/pom.xml
          mvn clean package -f ./tide-info/pom.xml

      - name: Docker Build and push for ReservationBooking
        uses: docker/build-push-action@v4
        with:
          context: ./reservation-booking
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reservation-booking:latest
            ghcr.io/${{ github.repository }}/reservation-booking:${{ github.ref_name }}
            
      - name: Docker Build and push for TransferReservation
        uses: docker/build-push-action@v4
        with:
          context: ./transfer-reservation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/transfer-reservation:latest
            ghcr.io/${{ github.repository }}/transfer-reservation:${{ github.ref_name }}
            
      - name: Docker Build and push for WeatherInfo
        uses: docker/build-push-action@v4
        with:
          context: ./weather-info
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/weather-info:latest
            ghcr.io/${{ github.repository }}/weather-info:${{ github.ref_name }}
            
      - name: Docker Build and push for TideInfo
        uses: docker/build-push-action@v4
        with:
          context: ./tide-info
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/tide-info:latest
            ghcr.io/${{ github.repository }}/tide-info:${{ github.ref_name }}
            
