apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-reservation
  labels:
    app: transfer-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-reservation
  template:
    metadata:
      labels:
        app: transfer-reservation
    spec:
      containers:
        - name: transfer-reservation
          image: "username/transfer-reservation:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
